
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: t1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: t1
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/cornelradu/argo-lux.git
    targetRevision: main
    path: teams/t1/dev
    helm:
      parameters:
      - name: spec.ingress.host
        value: dev.example.com
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
