
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
name: team-burnham
namespace: argocd
finalizers:
- resources-finalizer.argocd.argoproj.io
spec:
project: default
destination:
    namespace: team-burnham
    server: https://kubernetes.default.svc
source:
    repoURL: https://github.com/cornelradu/argo-lux
    targetRevision: main
    path: teams/team-burnham/dev
    helm:
        parameters:
        - name: spec.ingress.host
            value: dev.example.com
syncPolicy:
    automated:
    prune: true
    syncOptions:
    - CreateNamespace=true
                    
